[buildPlans.ConsolenaL]
    family = "ConsolenaL"
    spacing = "term"
    serifs = "sans"
    noCvSs = false
    exportGlyphNames = true

[buildPlans.ConsolenaL.namingOverride]
    copyright = "Veia Kurman 2025"
    designer = "Vim Lena"
    description = "Consolena is a monospace coding typeface designed for legibility and consistency. This is the regular width variation that includes some coding ligatures. Based on Iosevka Term SS04 by Belleve Invis."
    urlDesigner = "https://vimlena.com"
    license = "This font software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL. This font software is distributed on an ‘AS IS’ basis, without warranties or conditions of any kind, either express or implied. See the SIL Open Font license for the specific language, permissions and limitations governing your use of this font software."
    licenseURL = "https://openfontlicense.org/open-font-license-official-text/"
    sampleText = "Sphinx of black quartz, judge my vow. -> => <= != ; // </> ::"
    version = "1.0.0"

[buildPlans.ConsolenaL.variants]
    inherits = "ss04"

    [buildPlans.ConsolenaL.variants.design]
        two = "straight-neck-serifless"
        five = "oblique-arched-serifless"
        seven = "straight-serifless"
        nine = "straight-bar"
        zero = "oval-reverse-slashed-split"
        capital-b = "more-asymmetric-serifless"
        capital-g = "toothed-serifless-hooked"
        capital-j = "serifed-both-sides"
        capital-k = "curly-serifless"
        capital-m = "hanging-serifless"
        capital-q = "crossing-curly-tailed"
        capital-u = "toothed-serifless"
        capital-v = "curly-serifless"
        capital-x = "straight-bilateral-motion-serifed"
        b = "toothless-corner-serifless"
        e = "flat-crossbar"
        f = "flat-hook-serifless"
        i = "hooky"
        j = "serifed"
        k = "curly-serifless"
        l = "zshaped"
        q = "top-cut-tailed-serifless"
        r = "corner-hooked-serifless"
        v = "curly-serifless"
        w = "curly-flat-top-serifless"
        x = "semi-chancery-straight-serifless"
        tittle = "round"
        diacritic-dot = "round"
        braille-dot = "round"
        asterisk = "penta-mid"
        underscore = "high"
        brace = "curly"
        number-sign = "slanted-open"
        at = "fourfold-solid-inner"
        dollar = "slanted-open"
        cent = "slanted-open-cap"
        percent = "dots"
        question = "corner"
        lig-double-arrow-bar = "with-notch"
        lig-single-arrow-bar = "with-notch"

    [buildPlans.ConsolenaL.variants.italic]
        two = "straight-neck-serifed"
        five = "oblique-arched-serifed"
        seven = "bend-serifed"
        eight = "crossing-asymmetric"
        nine = "open-contour"
        capital-b = "more-asymmetric-unilateral-serifed"
        capital-c = "unilateral-inward-serifed"
        capital-d = "standard-unilateral-serifed"
        capital-e = "top-left-serifed"
        capital-f = "top-left-serifed"
        capital-g = "toothless-corner-inward-serifed-capped"
        capital-h = "top-left-bottom-right-serifed"
        capital-j = "serifed"
        capital-k = "curly-top-left-and-bottom-right-serifed"
        capital-l = "motion-serifed"
        capital-m = "hanging-motion-serifed"
        capital-n = "standard-motion-serifed"
        capital-p = "closed-motion-serifed"
        capital-r = "straight-top-left-and-bottom-right-serifed"
        capital-s = "unilateral-inward-serifed"
        capital-u = "tailed-serifless"
        capital-v = "curly-motion-serifed"
        capital-w = "straight-motion-serifed"
        capital-x = "straight-bilateral-motion-serifed"
        capital-y = "straight-motion-serifed"
        capital-z = "curly-bottom-serifed"
        a = "double-storey-tailed"
        b = "toothless-corner-serifed"
        c = "unilateral-inward-serifed"
        d = "tailed-serifed"
        e = "rounded"
        f = "flat-hook-extended"
        g = "single-storey-serifed"
        h = "tailed-motion-serifed"
        i = "zshaped"
        j = "diagonal-tailed-serifed"
        k = "curly-top-left-and-bottom-right-serifed"
        l = "serifed-flat-tailed"
        m = "tailed-top-left-serifed"
        n = "tailed-motion-serifed"
        p = "eared-motion-serifed"
        q = "top-cut-diagonal-tailed-serifless"
        r = "corner-hooked-top-serifed"
        s = "unilateral-inward-serifed"
        t = "diagonal-tailed-short-neck"
        u = "tailed-serifless"
        v = "curly-motion-serifed"
        w = "curly-flat-top-motion-serifed"
        x = "curly-bilateral-motion-serifed"
        y = "straight-turn-motion-serifed"
        z = "curly-bottom-serifed"

[buildPlans.ConsolenaL.ligations]
    inherits = "dlig"
    disables = [
        "colon-greater-as-colon-arrow",
        "eqexeq",
        "eqexeq-dl",
        "eqslasheq",
        "exeq",
        "exeqeq",
        "exeqeqeq",
        "exeqeqeq",
        "exeqeqeq",
        "hash-hash",
        "hash-hash-hash",
        "llgg",
        "llggeq",
        "ltgt-ne",
        "minus-minus",
        "minus-minus-minus",
        "plus-plus",
        "plus-plus-plus",
        "slasheq",
        "tilde-tilde",
        "tilde-tilde-tilde",
        "tildeeq",
        "underscore-underscore",
        "underscore-underscore-underscore",
    ]
    enables  = [
        "arrow-equal",
        "arrow-hyphen",
        "arrow-l",
        "arrow-l-equal",
        "arrow-l-wave",
        "arrow-lr",
        "arrow-lr-equal",
        "arrow-lr-wave",
        "arrow-r",
        "arrow-r-equal",
        "arrow-r-wave",
        "arrow-wave",
        "brace-bar",
        "brack-bar",
        "brst",
        "center-op-influence-colon",
        "center-op-influence-colon",
        "center-op-influence-dot",
        "center-op-influence-dot",
        "center-op-trigger-angle-inside",
        "center-op-trigger-angle-outside",
        "center-op-trigger-bar-l",
        "center-op-trigger-bar-r",
        "center-op-trigger-equal-l",
        "center-op-trigger-equal-r",
        "center-op-trigger-plus-minus-l",
        "center-op-trigger-plus-minus-r",
        "center-ops",
        "counter-arrow-equal",
        "counter-arrow-hyphen",
        "counter-arrow-l",
        "counter-arrow-l-equal",
        "counter-arrow-l-wave",
        "counter-arrow-r",
        "counter-arrow-r-equal",
        "counter-arrow-r-wave",
        "eqlt",
        "gteq",
        "html-comment",
        "kern-bars",
        "kern-dotty",
        "llgg",
        "logic",
        "lteq",
        "ltgt-diamond",
        "ltgt-diamond-tag",
        "ltgt-slash-tag",
        "markdown-checkboxes",
        "slash-asterisk",
        "trig",
    ]

[buildPlans.ConsolenaL.widths.Normal]
    shape = 600
    menu = 5
    css = "normal"

[buildPlans.ConsolenaL.slopes.Upright]
    angle = 0
    shape = "upright"
    menu = "upright"
    css = "normal"

[buildPlans.ConsolenaL.slopes.Italic]
    angle = 9
    shape = "italic"
    menu = "italic"
    css = "italic"

# npm run build -- contents::ConsolenaL
